# Generated by Django 4.1 on 2022-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.TextField()),
                ('rollnumber', models.TextField()),
                ('phonenumber', models.TextField()),
            ],
        ),
    ]
