# Generated by Django 4.1 on 2022-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.TextField()),
                ('present', models.TextField()),
                ('absent', models.TextField()),
            ],
        ),
    ]
