# Generated by Django 4.1 on 2022-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_attendance_absent_alter_attendance_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='absent',
            new_name='pre_abs',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='timedata',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
